/* Progressive enhancement shared by the process pages and both laboratories. */
(()=>{'use strict';const en=document.documentElement.lang==='en';const t=(cs,english)=>en?english:cs;
// Keep the model close to the introduction on narrow screens. Native disclosure
// leaves all camera, material and source controls available in one place.
const toolbar=document.querySelector('.toolbar');if(toolbar&&!document.body.classList.contains('qa')){const settings=document.createElement('details');settings.className='ux-viewer-settings';const summary=document.createElement('summary');summary.textContent=t('Pohled, povrch a prameny','View, surface and source controls');toolbar.before(settings);settings.append(summary,toolbar);const small=matchMedia('(max-width:700px)');settings.open=!small.matches;small.addEventListener('change',()=>{settings.open=!small.matches});}
const names={hero:['Celkový pohled','Overview'],photo1:['Pohled podle fotografie','Photograph viewpoint'],axis_front:['Průčelí','Front'],axis_right:['Pravá strana','Right side'],axis_back:['Zadní strana','Rear'],axis_left:['Levá strana','Left side'],front:['Průčelí','Front'],right:['Pravá strana','Right side'],back:['Zadní strana','Rear'],left:['Levá strana','Left side'],detail_facade:['Detail průčelí','Facade detail'],detail_corner:['Nároží','Corner'],detail_roof:['Vikýře a střecha','Dormers and roof'],detail_roof_frame:['Otevřený krov','Exposed roof frame'],detail_chimneys:['Komíny','Chimneys'],detail_damage:['Poškození omítky','Plaster damage'],detail_cornice:['Římsa a okap','Cornice and gutter'],detail_threshold:['Práh a vstup','Threshold and entrance'],detail_threshold_below:['Práh zespodu','Threshold from below'],detail_annex:['Dvorní přístavba','Rear annex'],detail_pipe:['Svod','Downpipe'],detail_shopfront:['Výkladnice','Shopfront'],detail_window:['Okno zleva','Window from left'],detail_window_right:['Okno zprava','Window from right'],detail_door:['Dveře','Door'],macro_sill:['Makro · parapet','Macro · sill'],macro_steps:['Makro · schod','Macro · step'],macro_arch:['Makro · obloukový lem','Macro · arch trim']};
const dirs={front:['zepředu','from front'],back:['zezadu','from rear'],left:['zleva','from left'],right:['zprava','from right'],side:['z boku','from side'],top:['shora','from above']};
function label(key,previous){if(names[key])return names[key][en?1:0];let m=key.match(/^opening_(.+)_(front|left|right)$/);if(m)return t('Otvor ','Opening ')+m[1]+' · '+dirs[m[2]][en?1:0];m=key.match(/^facade_(.+)$/);if(m)return t('Fasáda ','Facade ')+m[1];m=key.match(/^dormer_([ABC])_(.+)$/);if(m)return t('Vikýř ','Dormer ')+m[1]+' · '+(dirs[m[2]]?.[en?1:0]||m[2]);m=key.match(/^roof_(?:oblique_)?(front|back)_(left|right)$/);if(m)return t('Střecha · ','Roof · ')+({front_left:['přední levý roh','front left corner'],front_right:['přední pravý roh','front right corner'],back_left:['zadní levý roh','rear left corner'],back_right:['zadní pravý roh','rear right corner']}[m[1]+'_'+m[2]][en?1:0]);if(key==='detail_shopfront_right')return t('Výkladnice zprava','Shopfront from right');return previous;}
const facadeNames={A_street_long:['A · dlouhé průčelí','A · long street facade'],B_corner_return:['B · nárožní stěna','B · corner return'],C_rear_main:['C · dvorní stěna','C · rear facade'],D_annex_rear:['D · přístavba zezadu','D · rear annex'],E_annex_inner:['E · vnitřní stěna přístavby','E · inner annex wall']};
const view=document.getElementById('view');if(view){const rename=()=>{const selected=view.value;for(const o of view.options){o.textContent=label(o.value,o.textContent);const facade=o.value.replace(/^facade_/,'');if(facadeNames[facade])o.textContent=t('Fasáda ','Facade ')+facadeNames[facade][en?1:0];}
for(const option of [...view.children].filter(el=>el.tagName==='OPTION')){const key=option.value;const category=key.startsWith('opening_')?t('Okna a dveře','Windows and doors'):/^(roof_|dormer_)/.test(key)?t('Střecha a vikýře','Roof and dormers'):/^(detail_|macro_)/.test(key)?t('Detaily','Details'):t('Celkové pohledy','Overview viewpoints');let group=[...view.children].find(el=>el.tagName==='OPTGROUP'&&el.label===category);if(!group){group=document.createElement('optgroup');group.label=category;view.append(group)}group.append(option);}if(selected)view.value=selected;};rename();new MutationObserver(rename).observe(view,{childList:true});}
const status=document.getElementById('status');if(status){status.setAttribute('role','status');status.setAttribute('aria-live','polite');}
const viewLabel=document.getElementById('view-label');if(viewLabel&&view){const rename=()=>{const value=view.selectedOptions[0];if(value&&viewLabel.textContent!==value.textContent)viewLabel.textContent=value.textContent};view.addEventListener('change',()=>queueMicrotask(rename));new MutationObserver(rename).observe(viewLabel,{childList:true});}
// Static comparisons and source dialogs stay usable even if WebGL cannot load.
const dialog=document.getElementById('source-dialog');if(dialog){document.querySelector('#source,#source-button')?.addEventListener('click',()=>{if(!dialog.open)dialog.showModal()});document.getElementById('close-source')?.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});}
function enhance(stage){if(stage.dataset.uxReady)return;const imgs=stage.querySelectorAll('img');if(imgs.length<2||!stage.querySelector('img.after'))return;const input=stage.querySelector('input[type=range]')||stage.nextElementSibling?.querySelector('input[type=range]')||(stage.nextElementSibling?.matches('input[type=range]')?stage.nextElementSibling:null);if(!input)return;stage.dataset.uxReady='true';stage.classList.add('ux-compare');input.min='0';input.max='100';input.step='1';
for(const [i,img]of [...imgs].slice(0,2).entries()){img.draggable=false;const span=document.createElement('span');span.className='ux-compare-label '+(i?'ux-right':'ux-left');span.textContent=img.alt||t(i?'Po':'Před',i?'After':'Before');stage.append(span);}
const divider=document.createElement('span');divider.className='ux-divider';divider.setAttribute('aria-hidden','true');stage.append(divider);
const update=()=>{stage.style.setProperty('--split',input.value+'%');input.setAttribute('aria-valuetext',t(input.value+' % původního obrazu',input.value+'% of the original image'));};input.addEventListener('input',update);update();
let dragging=false;const move=e=>{const r=stage.getBoundingClientRect();input.value=Math.round(Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)));input.dispatchEvent(new Event('input',{bubbles:true}));};stage.addEventListener('pointerdown',e=>{if(e.target===input||e.button!==0)return;dragging=true;stage.setPointerCapture(e.pointerId);move(e)});stage.addEventListener('pointermove',e=>{if(dragging)move(e)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])stage.addEventListener(ev,()=>dragging=false);
}
const scan=()=>document.querySelectorAll('.compare,.swipe').forEach(enhance);scan();new MutationObserver(scan).observe(document.querySelector('main')||document.body,{childList:true,subtree:true});
// The source photographs and technical reports retain their original language.
if(en){const replacements={'Zvýraznit doplněné materiály':'Highlight inferred materials','Doplněné materiály':'Inferred materials','Regenerovaná HD · hypotéza':'Regenerated HD · hypothesis','Původní fotografická textura':'Original photographic texture','Zavřít':'Close'};document.querySelectorAll('option,button').forEach(el=>{if(replacements[el.textContent])el.textContent=replacements[el.textContent]});const source=document.querySelector('#source,#source-button');if(source)source.textContent='View source photographs and plans';const pipes=document.getElementById('pipes');if(pipes){const text=[...pipes.parentElement.childNodes].find(n=>n.nodeType===3&&n.textContent.includes('okapy'));if(text)text.textContent=' 3D gutters';}}
})();
