import * as T from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';
const en=new URLSearchParams(location.search).get('lang')==='en',text=(cs,eng)=>en?eng:cs,host=document.querySelector('#stage'),info=document.querySelector('#info'),status=document.querySelector('#status');if(en){document.documentElement.lang='en';document.querySelectorAll('[data-en]').forEach(e=>e.textContent=e.dataset.en);document.querySelector('#cp').ariaLabel='House number';}info.textContent=text('Výšky jsou pracovní odhady. Vyberte budovu kliknutím.','Heights are provisional. Click a building for details.');
try{
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;host.append(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.ariaLabel=text('Interaktivní model města','Interactive city model');const scene=new T.Scene();scene.background=new T.Color('#dce4df');const camera=new T.PerspectiveCamera(42,1,.5,15000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2-.03;controls.screenSpacePanning=true;controls.minDistance=25;controls.maxDistance=10000;scene.add(new T.HemisphereLight(0xffffff,0x819389,.65));const sun=new T.DirectionalLight(0xffffff,.5);sun.position.set(500,1000,300);scene.add(sun);
const data=await(await fetch('city.json')).json(),streets=new Map(data.streets.map(s=>[s.id,s])),meshes=[],bounds=new T.Box3();const colors=[0x795c40,0x896f4e,0x53684e,0x845e4a,0x4c6772,0x8a7955];const mats=colors.map(color=>new T.MeshLambertMaterial({color}));
for(const b of data.buildings){for(const part of b.parts){const shape=new T.Shape(part.outer.map(([x,z])=>new T.Vector2(x,-z)));for(const hole of part.holes)shape.holes.push(new T.Path(hole.map(([x,z])=>new T.Vector2(x,-z))));const geo=new T.ExtrudeGeometry(shape,{depth:b.heightM,bevelEnabled:false,steps:1});geo.rotateX(-Math.PI/2);const mesh=new T.Mesh(geo,mats[b.id%colors.length]);mesh.userData.building=b;scene.add(mesh);meshes.push(mesh);bounds.expandByObject(mesh);}}
const edges=[];for(const b of data.buildings)for(const part of b.parts)for(const ring of [part.outer,...part.holes])for(let i=0;i<ring.length;i++){const a=ring[i],c=ring[(i+1)%ring.length];edges.push(new T.Vector3(a[0],b.heightM+.05,a[1]),new T.Vector3(c[0],b.heightM+.05,c[1]));}scene.add(new T.LineSegments(new T.BufferGeometry().setFromPoints(edges),new T.LineBasicMaterial({color:0x314d43,transparent:true,opacity:.65})));const points=[];for(const s of data.streets)for(const path of s.paths||[])for(let i=1;i<path.length;i++)points.push(new T.Vector3(path[i-1][0],.15,path[i-1][1]),new T.Vector3(path[i][0],.15,path[i][1]));scene.add(new T.LineSegments(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:0x719286})));
const center=bounds.getCenter(new T.Vector3()),size=bounds.getSize(new T.Vector3()),extent=Math.max(size.x,size.z);let overhead=false,selected=null,helper=null;const base=new T.Mesh(new T.PlaneGeometry(size.x+100,size.z+100),new T.MeshBasicMaterial({color:0xcfd6c7}));base.rotation.x=-Math.PI/2;base.position.set(center.x,-.2,center.z);scene.add(base);
function fit(){const d=extent*.48/Math.tan(camera.fov*Math.PI/360)/Math.min(1,camera.aspect);controls.target.copy(center);camera.position.copy(center).add(new T.Vector3(.5,1,.8).normalize().multiplyScalar(d));if(overhead)camera.position.copy(center).add(new T.Vector3(0,d,.001));controls.update();}function view(top){overhead=top;const d=camera.position.distanceTo(controls.target);camera.position.copy(controls.target).add((top?new T.Vector3(0,1,.00001):new T.Vector3(.5,1,.8).normalize()).multiplyScalar(d));controls.update();}
function select(mesh,focus=false){selected=mesh;const b=mesh.userData.building,s=streets.get(b.streetId);if(helper){scene.remove(helper);helper.geometry.dispose();helper.material.dispose();}helper=new T.BoxHelper(mesh,0xd95728);scene.add(helper);info.textContent=text('Čp. ','No. ')+(b.cp??'—')+' · '+(s?.name1938||s?.name1964||text('ulice neurčena','street unknown'))+' · '+Math.round(b.areaM2)+' m² · '+text('zástupná výška ','proxy height ')+b.heightM+' m';document.body.dataset.selected=String(b.id);if(focus){const c=new T.Box3().setFromObject(mesh).getCenter(new T.Vector3());controls.target.copy(c);camera.position.copy(c).add((overhead?new T.Vector3(0,1,.00001):new T.Vector3(.5,1,.8).normalize()).multiplyScalar(140));controls.update();}}
document.querySelector('#reset').onclick=fit;document.querySelector('#top').onclick=()=>view(true);document.querySelector('#perspective').onclick=()=>view(false);function zoom(f){camera.position.sub(controls.target).multiplyScalar(f).add(controls.target);controls.update();}document.querySelector('#plus').onclick=()=>zoom(.7);document.querySelector('#minus').onclick=()=>zoom(1/.7);document.querySelector('#search').onsubmit=e=>{e.preventDefault();const cp=document.querySelector('#cp').value.trim();const matches=meshes.filter(m=>String(m.userData.building.cp)===cp);if(matches.length){select(matches[0],true);if(new Set(matches.map(m=>m.userData.building.id)).size>1)info.textContent+=' · '+text('více shod, zobrazen první záznam','multiple matches; showing the first');}else info.textContent=text('Čp. nebylo ve snímku nalezeno.','House number not found in this snapshot.');};
let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);const hit=ray.intersectObjects(meshes,false)[0];if(hit)select(hit.object);});
new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}).observe(host);renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();fit();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});status.textContent=data.buildings.length+text(' budov · ',' buildings · ')+data.streets.length+text(' ulic · snímek 2. 9. 2026',' streets · snapshot 2 Sep 2026');document.body.dataset.ready='true';
}catch(e){status.textContent=text('Mapu se nepodařilo načíst: ','Could not load the map: ')+e.message;console.error(e);}


