import * as THREE from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
const q=new URLSearchParams(location.search),en=q.get('lang')==='en',status=document.getElementById('status'),host=document.getElementById('stage');if(en){document.documentElement.lang='en';document.querySelectorAll('[data-en]').forEach(x=>x.textContent=x.dataset.en);document.getElementById('reset').textContent='Fit model';document.getElementById('rear').textContent='Rear';}
const scene=new THREE.Scene();scene.background=new THREE.Color('#d9dfe0');const camera=new THREE.PerspectiveCamera(38,1,.01,1000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;host.appendChild(renderer.domElement);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xffffff,0x58626a,1.0));const light=new THREE.DirectionalLight(0xfff5e6,1.5);scene.add(light);const fill=new THREE.DirectionalLight(0xe3efff,.5);fill.position.set(-4,2,-3);scene.add(fill);
let model,materials=[],extent=1;function fit(back=false){const distance=extent*(q.get('model')==='mirove'?.6:.9)/Math.sin(camera.fov*Math.PI/360)/Math.min(1,camera.aspect);camera.position.copy(new THREE.Vector3(back?-.7:.7,q.get('model')==='mirove'?.95:.4,back?-1.4:1.4).normalize().multiplyScalar(distance));orbit.target.set(0,0,0);camera.near=extent/200;camera.far=extent*20;orbit.minDistance=extent/50;orbit.maxDistance=extent*10;camera.updateProjectionMatrix();orbit.update()}
function lighting(){const a=Number(document.getElementById('light').value)*Math.PI/180;light.position.set(Math.sin(a)*5,3,Math.cos(a)*5)}lighting();document.getElementById('light').oninput=lighting;
function apply(){const neutral=document.getElementById('neutral').checked,normals=document.getElementById('normals').checked;for(const m of materials){m.map=neutral?null:m.userData.originalMap;m.color.copy(neutral?new THREE.Color(.65,.65,.65):m.userData.originalColor);if(m.normalScale)m.normalScale.copy(normals?m.userData.originalNormalScale:new THREE.Vector2(0,0));m.wireframe=document.getElementById('wire').checked;m.needsUpdate=true}}
for(const id of ['wire','neutral','normals'])document.getElementById(id).onchange=apply;document.getElementById('reset').onclick=()=>fit();document.getElementById('rear').onclick=()=>fit(true);document.getElementById('detail').onclick=()=>{camera.position.lerp(orbit.target,.45);orbit.update()};
new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()}).observe(host);renderer.setAnimationLoop(()=>{orbit.update();renderer.render(scene,camera)});
try{const all=await(await fetch('models.json')).json();const row=all.find(x=>x.id===q.get('model'))||all.find(x=>x.id==='262');document.getElementById('title').textContent=row[en?'en':'cs'];const gltf=await new GLTFLoader().loadAsync(row.file||row.id+'.glb',p=>{status.textContent=(en?'Loading':'Načítání')+' · '+(p.loaded/1048576).toFixed(1)+' / '+row.mb+' MB'});model=gltf.scene;const box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());const group=new THREE.Group();group.add(model);group.position.copy(center).multiplyScalar(-1);scene.add(group);group.updateMatrixWorld(true);extent=Math.max(size.x,size.y,size.z);model.traverse(o=>{if(o.isMesh)for(const m of(Array.isArray(o.material)?o.material:[o.material]))if(!materials.includes(m)){for(const t of [m.map,m.normalMap,m.roughnessMap])if(t){t.anisotropy=Math.min(16,renderer.capabilities.getMaxAnisotropy());t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;t.generateMipmaps=true;t.needsUpdate=true;}m.userData.originalMap=m.map;m.userData.originalColor=m.color.clone();m.userData.originalNormalScale=m.normalScale?.clone()||new THREE.Vector2(1,1);materials.push(m)}});document.getElementById('normals').disabled=!materials.some(m=>m.normalMap);fit();status.textContent=en?'Loaded · drag to rotate, scroll/pinch to zoom':'Načteno · tažením otáčejte, kolečkem či gestem přibližujte';document.body.dataset.loaded=row.id;document.body.dataset.normalMaps=materials.filter(m=>m.normalMap).length;}catch(e){status.textContent=(en?'Loading failed: ':'Chyba načtení: ')+e.message;console.error(e)}
