import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
if(new URLSearchParams(location.search).has('qa'))document.body.classList.add('qa');
const $=id=>document.getElementById(id),host=$('canvas');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.8;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#dddcd2');scene.add(new THREE.HemisphereLight(0xffffff,0x7d8074,1.05));const sun=new THREE.DirectionalLight(0xfff7e8,1.0);sun.position.set(-12,24,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:.1,far:90});sun.shadow.bias=-.0001;sun.shadow.normalBias=.015;sun.target.position.set(6.8,5,-5);scene.add(sun,sun.target);
const camera=new THREE.PerspectiveCamera(38,1,.01,200),control=new OrbitControls(camera,renderer.domElement);control.enableDamping=true;
const clay=new THREE.MeshStandardMaterial({color:'#63756b',roughness:.9}),highlight=new THREE.MeshStandardMaterial({color:'#df7435',roughness:.9});
const views={detail_steps:{label:'Steps and threshold',p:[-1.1,1.65,2.8],t:[1.23,.5,.25]},detail_steps_right:{label:'Steps from the right',p:[3.7,1.6,2.7],t:[1.23,.5,.25]},detail_pipe:{label:'Right downpipe',p:[17,6.7,5],t:[13.25,4.7,0]},detail_pipe_top:{label:'Downpipe connection',p:[15.3,7.5,2.7],t:[13.3,6.5,0]},axis_front:{label:'Front',p:[6.87,6,25],t:[6.87,6,0]},axis_right:{label:'Right side',p:[37,7,-6.9],t:[6.87,6,-6.9]},axis_back:{label:'Rear',p:[6.87,7,-38],t:[6.87,6,-6.9]},axis_left:{label:'Left side',p:[-24,7,-6.9],t:[6.87,6,-6.9]},roof_oblique_front_left:{label:'Roof · front left',p:[-15,23,22],t:[6.87,7,-5]},roof_oblique_front_right:{label:'Roof · front right',p:[29,23,22],t:[6.87,7,-5]},roof_oblique_back_left:{label:'Roof · rear left',p:[-15,23,-33],t:[6.87,7,-6]},roof_oblique_back_right:{label:'Roof · rear right',p:[29,23,-33],t:[6.87,7,-6]},detail_facade:{label:'Facade detail',p:[6.8,4.2,19],t:[6.8,3.7,0]},detail_window:{label:'Window returns from left',p:[2.5,5.7,4.5],t:[5.8,5.4,0]},detail_window_right:{label:'Window returns from right',p:[9.6,5.7,4.5],t:[8.05,5.4,0]},detail_door:{label:'Door',p:[-1,2.2,4.0],t:[1.2,1.3,-.1]},detail_corner:{label:'Corner',p:[-4,4,5],t:[.4,3.6,-.2]},detail_cornice:{label:'Cornice and gutter',p:[8,9.0,5.2],t:[6.5,6.9,0]},detail_damage:{label:'Plaster damage',p:[4.2,4.8,4],t:[4.2,4.8,0]},detail_roof:{label:'Dormers',p:[3.6,12.3,9],t:[7.1,9,-2.4]}};
for(const [key,v]of Object.entries(views)){const op=document.createElement('option');op.value=key;op.textContent=v.label;$('view').appendChild(op)}
let before,after,mode='after',current='axis_front';function setView(key){const v=views[key];current=key;camera.position.fromArray(v.p);control.target.fromArray(v.t);control.update();$('view').value=key;$('view-label').textContent=v.label;render()}
function setMode(m){mode=m;after.traverse(o=>{if(o.isMesh&&/gutter/i.test(o.name))o.visible=m!=='no-metal'});before.visible=m==='before';after.visible=m!=='before';after.traverse(o=>{if(o.isMesh)o.material=m==='clay'?clay:m==='generated'?(Array.isArray(o.userData.originalMaterial)?o.userData.originalMaterial.map(mat=>mat.userData.generated_unobserved_surface?highlight:mat):o.userData.originalMaterial.userData.generated_unobserved_surface?highlight:o.userData.originalMaterial):o.userData.originalMaterial});document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));render()}
function render(){renderer.render(scene,camera)}function resize(){renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();render()}new ResizeObserver(resize).observe(host);
function loop(){requestAnimationFrame(loop);control.update();render()}loop();
const loader=new GLTFLoader();try{[before,after]=await Promise.all(['cp261_v7.glb','cp261_v8.glb'].map(async f=>(await loader.loadAsync('./models/'+f)).scene));scene.add(before,after);for(const model of [before,after])model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const mat of (Array.isArray(o.material)?o.material:[o.material])){if(mat.map)mat.map.anisotropy=Math.min(16,renderer.capabilities.getMaxAnisotropy())}}});after.traverse(o=>{if(o.isMesh)o.userData.originalMaterial=o.material});$('load').remove();setView('roof_oblique_front_left');setMode('after');window.qa={ready:true,views,setView,setMode,render,snapshot:()=>({view:current,mode,position:camera.position.toArray(),target:control.target.toArray(),fov:camera.fov,aspect:camera.aspect})};}catch(e){$('load').textContent='Model could not be loaded: '+e.message;console.error(e)}
$('view').addEventListener('change',e=>setView(e.target.value));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$('source-button').onclick=()=>$('source-dialog').showModal();$('close-source').onclick=()=>$('source-dialog').close();renderer.domElement.addEventListener('dblclick',()=>$('source-dialog').showModal());
fetch('./qa/comparisons-en.json').then(r=>r.ok?r.json():[]).then(data=>{for(const c of data){const a=document.createElement('article');a.className='comparison';a.innerHTML=`<h3>${c.title}</h3><p>${c.note}</p><div class="pair"><figure><img src="./qa/${c.before}" alt="Before: ${c.title}" loading="lazy"><figcaption>BEFORE · V6</figcaption></figure><figure><img src="./qa/${c.after}" alt="After: ${c.title}" loading="lazy"><figcaption>AFTER · V7</figcaption></figure></div>`;if(true){const swipe=document.createElement('div');swipe.innerHTML=`<div class="swipe"><img src="./qa/${c.before}" alt="Before"><img class="after" src="./qa/${c.after}" alt="After"></div><label>Move the BEFORE / AFTER boundary <input class="slider" aria-label="Boundary: ${c.title}" type="range" min="0" max="100" value="50"></label>`;swipe.querySelector('input').oninput=e=>swipe.querySelector('.swipe').style.setProperty('--split',e.target.value+'%');a.appendChild(swipe)}$('comparisons').appendChild(a)}if(!data.length)$('comparisons').innerHTML='<p>Afterrovnání můžete už teď přepínat tlačítky Nová verze / Převzatá v5 při nezměněném pohledu. Snímky kontrolní sady se právě připravují.</p>'}).catch(()=>{});
fetch('./revision-v8/visual_qa.json').then(r=>r.json()).then(q=>{$('qa-status').textContent=q.summary_en}).catch(()=>{});


$('lighting').onchange=e=>{renderer.toneMappingExposure=e.target.value==='previous'?1:.8;render()};
