(()=>{'use strict';const data=JSON.parse(document.getElementById('source-data').textContent),$=id=>document.getElementById(id),notes=$('notes-panel'),lab=$('lab-dialog');
 const current=()=>Math.max(0,(Number(location.hash.match(/slide-(\d+)/)?.[1])||1)-1);
 function updateNotes(){const page=data.pages[current()]||data.pages[0];$('notes-title').textContent=page.title;$('notes-original').textContent=page.text;$('notes-links').replaceChildren();for(const link of page.links){const a=document.createElement('a');a.href=link.url||'#slide-'+link.page;a.textContent=link.url||'Snímek '+link.page;if(!link.url)a.addEventListener('click',()=>notes.close());$('notes-links').append(a);}}
 $('notes-toggle').addEventListener('click',()=>{updateNotes();notes.showModal();});$('lab-toggle').addEventListener('click',()=>lab.showModal());
 $('text-toggle').addEventListener('click',()=>{const on=document.body.classList.toggle('textual');$('text-toggle').setAttribute('aria-pressed',String(on));});
 function activate(all=false){const active=all?[...document.querySelectorAll('.page-svg')]:[document.querySelector('#slide-'+(current()+1)+' .page-svg')];for(const object of active.filter(Boolean))if(!object.hasAttribute('data')){object.addEventListener('load',()=>{object.dataset.loaded='true';},{once:true});object.data=object.dataset.src;}}
 new MutationObserver(()=>activate()).observe($('counter'),{childList:true});activate();$('reading').addEventListener('click',()=>{if(document.body.classList.contains('reading'))activate(true);});
 for(const button of document.querySelectorAll('.source-zoom'))button.addEventListener('click',()=>{const dialog=$('image-view');dialog.querySelector('img').hidden=true;let object=dialog.querySelector('object');if(!object){object=document.createElement('object');object.type='image/svg+xml';object.className='source-svg-zoom';object.tabIndex=-1;dialog.append(object);}object.data=button.dataset.image;dialog.showModal();});
 async function print(){activate(true);$('print-button').disabled=true;$('print-button').textContent='Připravuji tisk…';const objects=[...document.querySelectorAll('.page-svg')];try{await Promise.all(objects.map(o=>new Promise((resolve,reject)=>{if(o.dataset.loaded==='true'){resolve();return;}const timeout=setTimeout(()=>reject(Error('load')),30000);o.addEventListener('load',()=>{clearTimeout(timeout);resolve();},{once:true});})));window.print();}catch{$('print-button').title='Příprava tisku se nezdařila; použijte původní PDF.';}finally{$('print-button').disabled=false;$('print-button').textContent='Tisk';}}
 $('print-button').addEventListener('click',print);addEventListener('beforeprint',()=>activate(true));
 const fit=()=>{const deck=$('deck');document.documentElement.style.setProperty('--source-height',Math.max(100,deck.clientHeight-60)+'px');};new ResizeObserver(fit).observe($('deck'));fit();
 addEventListener('hashchange',updateNotes);document.addEventListener('keydown',e=>{if(document.querySelector('dialog:modal')||e.ctrlKey||e.altKey||e.metaKey||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key.toLowerCase()==='n'){updateNotes();notes.showModal();}if(e.key.toLowerCase()==='i')lab.showModal();});
})();
