(()=>{'use strict';const meta=JSON.parse(document.getElementById('source-data').textContent),kind=meta.lab,$=id=>document.getElementById(id),canvas=$('lab-canvas'),ctx=canvas.getContext('2d'),settings=$('lab-settings'),values={},inputs={},defaults={};
const clamp=(v,a=0,b=255)=>Math.min(b,Math.max(a,v)),line=(x1,y1,x2,y2,color='#245d72',width=2)=>{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();},dot=(x,y,r=5,color='#b85021')=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,2*Math.PI);ctx.fill();},text=(s,x,y)=>{ctx.fillStyle='#203039';ctx.font='16px Segoe UI';ctx.fillText(s,x,y);},clear=()=>{ctx.clearRect(0,0,640,380);ctx.fillStyle='#fff';ctx.fillRect(0,0,640,380);};
function range(id,label,min,max,step,value){const wrap=document.createElement('label'),name=document.createTextNode(label+' '),out=document.createElement('output'),input=document.createElement('input');input.type='range';Object.assign(input,{id,min:String(min),max:String(max),step:String(step),value:String(value)});out.htmlFor=id;wrap.append(name,out,input);settings.append(wrap);inputs[id]=input;values[id]=value;defaults[id]=value;input.addEventListener('input',()=>{values[id]=Number(input.value);out.value=input.value;render();});out.value=input.value;}
function select(id,label,choices,value){const wrap=document.createElement('label'),input=document.createElement('select');input.id=id;for(const [v,title]of choices){const option=document.createElement('option');option.value=v;option.textContent=title;input.append(option);}input.value=value;wrap.append(document.createTextNode(label),input);settings.append(wrap);inputs[id]=input;values[id]=value;defaults[id]=value;input.addEventListener('change',()=>{values[id]=input.value;render();});}
let points=[[.13,.17],[.3,.23],[.74,.35],[.7,.67],[.81,.8],[.2,.72],[.46,.55]];
const initialPoints=points.map(p=>[...p]);
switch(kind){
case 'geometry':range('resolution','Dělení mřížky',1,10,1,4);range('amplitude','Výška deformace',0,1,.05,.35);$('lab-limits').textContent='Pravidelná mřížka se dvěma trojúhelníky na buňku; nejde o běžící bpy skript.';break;
case 'bezier':range('parameter','Parametr t',0,1,.01,.5);range('control1','Výška řídicího bodu P1',0,1,.01,.1);range('control2','Výška řídicího bodu P2',0,1,.01,.9);$('lab-limits').textContent='Kubická Bézierova křivka, nikoli obecná NURBS.';break;
case 'ray':range('angle','Směr paprsku (°)',-40,40,1,-12);range('radius','Poloměr koule',.3,1.4,.05,.9);$('lab-limits').textContent='Rovinný řez paprskem a koulí. Kořen kvadratické rovnice dává vzdálenost po paprsku.';break;
case 'normal':range('red','R normálové mapy',0,255,1,128);range('green','G normálové mapy',0,255,1,128);$('lab-limits').textContent='N = normalize(2R/255−1, 2G/255−1, 1). Zobrazuje pouze Lambertův člen, nikoli celý PBR model.';break;
case 'appearance':range('light','Směr světla (°)',0,80,1,30);range('view','Směr pohledu (°)',0,80,1,20);$('lab-limits').textContent='Syntetická směrově proměnná textura; není naměřená BTF a nemá kalibrované fyzikální jednotky.';break;
case 'brightness':range('brightness','Přičtení k RGB kanálům',-100,100,1,0);$('lab-limits').textContent='Nový kanál = clamp(původní + hodnota, 0, 255). Nejde o úpravu vnímaného jasu.';break;
case 'convolution':select('pattern','Vstup',[['impulse','Jednotkový impuls'],['checker','Šachovnice']],'impulse');select('kernel','Jádro',[['mean','Průměr 3×3'],['identity','Identita'],['sobel','Sobel X'],['sharpen','Doostření']],'mean');$('lab-limits').textContent='3×3 konvoluce se symetrickými jádry kromě Sobelu. Pro Sobel se používá korelace (běžná implementační konvence), mimo obraz jsou nuly. Náhled ořezává hodnoty do 0–255; čísla zobrazují výsledek před ořezáním.';break;
case 'fourier':range('frequency','Frekvence signálu',1,16,1,4);range('blur','Rozmazání',0,3,.1,1);range('regularization','Wienerova konstanta K',0,.2,.005,.03);$('lab-limits').textContent='64 vzorků a skutečná diskrétní Fourierova transformace. H je známý Gaussův přenos; K je zjednodušený konstantní poměr šumu/signálu, nikoli odhad ze skutečného obrazu.';break;
case 'partition':range('depth','Maximální hloubka',1,5,1,3);$('lab-limits').textContent='2D quadtree jako analogie prostorového dělení. Dělí se buňky s více než dvěma body. Kliknutí do náhledu přidá bod; nejde o 3D octree.';canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect();const x=(e.clientX-r.x)*640/r.width,y=(e.clientY-r.y)*380/r.height;if(x>=60&&x<=580&&y>=30&&y<=350&&points.length<64){points.push([Math.min(1-Number.EPSILON,(x-60)/520),Math.min(1-Number.EPSILON,(y-30)/320)]);render();}});break;
default:throw Error('Unknown lab '+kind);
}
const reset=document.createElement('button');reset.id='lab-reset';reset.type='button';reset.textContent='Reset';reset.addEventListener('click',()=>{for(const[id,value]of Object.entries(defaults)){values[id]=value;inputs[id].value=String(value);const out=inputs[id].parentElement.querySelector('output');if(out)out.value=String(value);}points=initialPoints.map(p=>[...p]);render();});settings.append(reset);
const dft=signal=>signal.map((_,k)=>{let re=0,im=0;for(let n=0;n<signal.length;n++){const a=2*Math.PI*k*n/signal.length;re+=signal[n]*Math.cos(a);im-=signal[n]*Math.sin(a);}return[re,im];});
const inverse=spec=>spec.map((_,n)=>spec.reduce((sum,[re,im],k)=>sum+re*Math.cos(2*Math.PI*k*n/spec.length)-im*Math.sin(2*Math.PI*k*n/spec.length),0)/spec.length);
function evaluate(){switch(kind){
case 'geometry':{const n=values.resolution;return {vertices:(n+1)**2,triangles:2*n*n,resolution:n,amplitude:values.amplitude};}
case 'bezier':{const t=values.parameter,p=[[0,.5],[.25,values.control1],[.75,values.control2],[1,.5]],w=[(1-t)**3,3*(1-t)**2*t,3*(1-t)*t*t,t**3];return{point:[0,1].map(d=>p.reduce((sum,q,i)=>sum+w[i]*q[d],0)),controlPoints:p,parameter:t};}
case 'ray':{const a=values.angle*Math.PI/180,d=[Math.cos(a),Math.sin(a)],o=[-3,1],b=2*(o[0]*d[0]+o[1]*d[1]),c=10-values.radius**2,disc=b*b-4*c;const ts=disc<0?[]:[(-b-Math.sqrt(disc))/2,(-b+Math.sqrt(disc))/2].filter(t=>t>=0);return{direction:d,origin:o,discriminant:disc,t:ts.length?Math.min(...ts):null,point:ts.length?o.map((v,i)=>v+Math.min(...ts)*d[i]):null};}
case 'normal':{const raw=[2*values.red/255-1,2*values.green/255-1,1],length=Math.hypot(...raw),n=raw.map(x=>x/length),l=[-.3,.4,.8660254037844386],intensity=Math.max(0,n.reduce((s,x,i)=>s+x*l[i],0));return{normal:n,intensity,color:[values.red,values.green,255]};}
case 'appearance':return{light:values.light,view:values.view,measured:false};
case 'brightness':return{offset:values.brightness,firstPixel:[clamp(values.brightness),clamp(values.brightness),clamp(80+values.brightness),255]};
case 'convolution':{const n=8,input=Array.from({length:64},(_,i)=>values.pattern==='impulse'?(i===36?255:0):((Math.floor(i/8/2)+Math.floor(i%8/2))%2)*255);const kernels={mean:Array(9).fill(1/9),identity:[0,0,0,0,1,0,0,0,0],sobel:[-1,0,1,-2,0,2,-1,0,1],sharpen:[0,-1,0,-1,5,-1,0,-1,0]},kernel=kernels[values.kernel];const output=input.map((_,i)=>{let sum=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const y=Math.floor(i/n)+dy,x=i%n+dx;if(x>=0&&x<n&&y>=0&&y<n)sum+=input[y*n+x]*kernel[(dy+1)*3+dx+1];}return sum;});return{input,output,kernel,center:output[36],kernelSum:kernel.reduce((a,b)=>a+b,0),operation:values.kernel==='sobel'?'correlation':'convolution'};}
case 'fourier':{const n=64,clean=Array.from({length:n},(_,i)=>Math.sin(2*Math.PI*values.frequency*i/n)),spec=dft(clean),transfer=spec.map((_,k)=>Math.exp(-2*Math.PI**2*values.blur*(Math.min(k,n-k)/n)**2)),blurSpec=spec.map((c,k)=>c.map(v=>v*transfer[k])),observed=inverse(blurSpec),filteredSpec=blurSpec.map((c,k)=>c.map(v=>v*transfer[k]/(transfer[k]**2+values.regularization))),restored=inverse(filteredSpec),magnitudes=spec.map(c=>Math.hypot(...c)/(n/2));return{clean,observed,restored,magnitudes,peak:magnitudes.slice(0,33).indexOf(Math.max(...magnitudes.slice(0,33))),K:values.regularization};}
case 'partition':{const cells=[];function split(x,y,size,pts,depth){cells.push({x,y,size,depth,count:pts.length});if(pts.length<=2||depth>=values.depth)return;for(let dy=0;dy<2;dy++)for(let dx=0;dx<2;dx++){const xx=x+dx*size/2,yy=y+dy*size/2;split(xx,yy,size/2,pts.filter(p=>p[0]>=xx&&p[0]<xx+size/2&&p[1]>=yy&&p[1]<yy+size/2),depth+1);}}split(0,0,1,points,0);return{cells,points:points.map(p=>[...p]),nodes:cells.length,maxDepth:Math.max(...cells.map(c=>c.depth))};}
}}
function render(){clear();const data=evaluate();let result='';switch(kind){
case 'geometry':{const n=data.resolution,project=(x,y)=>[320+(x-y)*180,210+(x+y-1)*70-Math.sin(Math.PI*x)*Math.sin(Math.PI*y)*values.amplitude*140];for(let y=0;y<=n;y++)for(let x=0;x<=n;x++){const p=project(x/n,y/n);if(x<n){const q=project((x+1)/n,y/n);line(...p,...q);}if(y<n){const q=project(x/n,(y+1)/n);line(...p,...q);}dot(...p,3);}result=`Vrcholů: ${data.vertices}\nTrojúhelníků: ${data.triangles}\n(x,y,z) = (i/n, j/n, A·sin(πi/n)·sin(πj/n))`;break;}
case 'bezier':{const p=data.controlPoints.map(([x,y])=>[60+520*x,330-280*y]);for(let i=0;i<3;i++)line(...p[i],...p[i+1],'#abb9c3',1);ctx.strokeStyle='#245d72';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(...p[0]);ctx.bezierCurveTo(...p[1],...p[2],...p[3]);ctx.stroke();p.forEach((q,i)=>{dot(...q,5);text('P'+i,q[0]+6,q[1]-6);});dot(60+520*data.point[0],330-280*data.point[1],8,'#b85021');result=`t = ${data.parameter.toFixed(2)}\nB(t) = (${data.point.map(x=>x.toFixed(4)).join(', ')})\nΣ Bernsteinových vah = 1`;break;}
case 'ray':{const project=([x,y])=>[370+x*85,205-y*85];ctx.strokeStyle='#245d72';ctx.lineWidth=3;ctx.beginPath();ctx.arc(370,205,values.radius*85,0,2*Math.PI);ctx.stroke();const end=data.origin.map((x,i)=>x+6*data.direction[i]);line(...project(data.origin),...project(end),'#b85021',3);dot(...project(data.origin),6);if(data.point)dot(...project(data.point),8,'#245d72');result=`Δ = ${data.discriminant.toFixed(5)}\n${data.t===null?'Bez průsečíku':`První průsečík t = ${data.t.toFixed(5)}\nP = (${data.point.map(x=>x.toFixed(4)).join(', ')})`}`;break;}
case 'normal':{const n=data.normal;ctx.fillStyle=`rgb(${values.red},${values.green},255)`;ctx.fillRect(50,65,220,220);ctx.fillStyle=`rgb(${Math.round(data.intensity*245)},${Math.round(data.intensity*205)},${Math.round(data.intensity*155)})`;ctx.beginPath();ctx.arc(470,175,105,0,2*Math.PI);ctx.fill();line(160,175,160+n[0]*100,175-n[1]*100,'#203039',4);text('RGB normála',70,320);text('Lambertův člen',390,320);result=`N = (${n.map(x=>x.toFixed(4)).join(', ')})\nmax(0,N·L) = ${data.intensity.toFixed(4)}`;break;}
case 'appearance':{const image=ctx.createImageData(300,300),li=values.light*Math.PI/180,vi=values.view*Math.PI/180;for(let y=0;y<300;y++)for(let x=0;x<300;x++){const i=(y*300+x)*4,v=clamp(.52+.18*Math.cos(x*.15)+.13*Math.cos(y*.3)*Math.cos(vi)+.14*Math.cos(li)+.12*Math.sin(x*.1+y*.1+vi)*Math.sin(li),0,1);image.data[i]=v*235;image.data[i+1]=v*185;image.data[i+2]=v*125;image.data[i+3]=255;}ctx.putImageData(image,170,25);result=`Světlo ${values.light}° · pohled ${values.view}°\nSyntetická textura; nenaměřená BTF.\nZměna směru mění i lokální vzor, nejen celkový jas.`;break;}
case 'brightness':{const image=ctx.createImageData(256,128);for(let y=0;y<128;y++)for(let x=0;x<256;x++){const i=(y*256+x)*4,offset=x<128?0:values.brightness,xx=x%128;image.data[i]=clamp(2*xx+offset);image.data[i+1]=clamp(2*y+offset);image.data[i+2]=clamp(80+offset);image.data[i+3]=255;}const temp=document.createElement('canvas');temp.width=256;temp.height=128;temp.getContext('2d').putImageData(image,0,0);ctx.drawImage(temp,35,55,570,285);text('Vstup',60,360);text('Náhled',355,360);result=`První RGB pixel výstupu: ${data.firstPixel.slice(0,3).join(', ')}\nOřezání: 0…255`;break;}
case 'convolution':{for(const [arr,start]of[[data.input,30],[data.output,350]])for(let y=0;y<8;y++)for(let x=0;x<8;x++){ctx.fillStyle=`rgb(${clamp(arr[y*8+x])},${clamp(arr[y*8+x])},${clamp(arr[y*8+x])})`;ctx.fillRect(start+x*32,35+y*32,31,31);}text('Vstup',40,325);text('Výstup',360,325);result=`Jádro:\n${[0,1,2].map(y=>data.kernel.slice(y*3,y*3+3).map(v=>v.toFixed(3)).join('  ')).join('\n')}\nSoučet: ${data.kernelSum.toFixed(3)}\nPixel (4,4) před ořezáním: ${data.center.toFixed(4)}`;break;}
case 'fourier':{function plot(signal,y,color){for(let i=0;i<signal.length-1;i++)line(35+i*570/63,y-signal[i]*48,35+(i+1)*570/63,y-signal[i+1]*48,color,2);}plot(data.clean,80,'#245d72');plot(data.observed,180,'#b85021');plot(data.restored,280,'#588b54');text('Původní signál',40,20);text('Po známém rozmazání',40,125);text('Wienerova regularizace',40,225);result=`DFT maximum k = ${data.peak}\n|F[k]|/(N/2) = ${data.magnitudes[data.peak].toFixed(5)}\nG(k) = H(k)/(H(k)² + K)\nK = ${data.K.toFixed(3)} (bez přidaného šumu)`;break;}
case 'partition':{for(const c of data.cells){ctx.strokeStyle='#94adb5';ctx.lineWidth=1;ctx.strokeRect(60+c.x*520,30+c.y*320,c.size*520,c.size*320);}for(const p of points)dot(60+p[0]*520,30+p[1]*320,5);result=`Bodů: ${points.length}\nUzly stromu: ${data.nodes}\nDosažená hloubka: ${data.maxDepth}\nKliknutím do mřížky přidejte bod.`;break;}
} $('lab-result').textContent=result;window.PGALab={kind,values,evaluate};}
render();})();
